# Generated by Django 5.1.6 on 2025-03-03 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
